# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c26c777218ba71d4b7a2506fe9e0c1f304dcc4a85b0fa78acf10a70214de8cf27aa21435bb9090d0e6f81895846044d03c26919d7f76065a028232db8f7ba0c1

test:
  secret_key_base: 2d9f5e1db7752413b8aa1f79e885a86233d33a25f60b2b1e7f388cb50049f1694ea838bc5fa43e4c83ce64baa64740a89454672545bad28c860dfbd7c67cb340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
